#include "pch.h"
#include "tasks.h"

// note that usvfs is the only project that has to be built for both 32- and
// 64-bit architectures
//
// prebuilts are typically only used when building on appveyor, so they reuse
// whatever was last built with contiguous integration
//
// the files generated by CI are called "artifacts", they can be seen on
// https://ci.appveyor.com/project/ModOrganizer2/usvfs, by clicking on a
// platform at the bottom, then the "Artifacts" tab

namespace mob::tasks {

    usvfs::usvfs() : basic_task("usvfs") {}

    std::string usvfs::version()
    {
        return conf().version().get("usvfs");
    }

    bool usvfs::prebuilt()
    {
        return false;
    }

    fs::path usvfs::source_path()
    {
        return conf().path().build() / "usvfs";
    }

    void usvfs::do_clean(clean c)
    {
        // delete the whole directory
        if (is_set(c, clean::reclone)) {
            git_wrap::delete_directory(cx(), source_path());

            // nothing more to do
            return;
        }

        if (is_set(c, clean::rebuild)) {
            // msbuild clean
            run_tool(create_msbuild_tool(arch::x86, msbuild::clean));
            run_tool(create_msbuild_tool(arch::x64, msbuild::clean));
        }
    }

    void usvfs::do_fetch()
    {
        fetch_from_source();
    }

    void usvfs::do_build_and_install()
    {
        build_and_install_from_source();
    }

    void usvfs::fetch_from_source()
    {
        run_tool(make_git()
                     .url(make_git_url(task_conf().mo_org(), "usvfs"))
                     .branch(version())
                     .root(source_path()));
    }

    void usvfs::build_and_install_from_source()
    {
        run_tool(create_msbuild_tool(arch::x86));
        run_tool(create_msbuild_tool(arch::x64));
    }

    msbuild usvfs::create_msbuild_tool(arch a, msbuild::ops o) const
    {
        // usvfs doesn't use "Win32" for 32-bit, it uses "x86"
        //
        // note that usvfs_proxy has a custom build step in Release that runs
        // usvfs/vsbuild/stage_helper.cmd, which copies everything into
        // install/

        const std::string plat = (a == arch::x64 ? "x64" : "x86");

        // udis requires python in its custom build step, so make sure it's on the
        // path
        //
        // BOOST_PATH is in the env because external_dependencies.props will
        // use it if it exists or reverts to a hardcoded path which might not be using
        // the same version as mob if it wasn't updated
        return std::move(
            msbuild(o)
                .platform(plat)
                .targets({"usvfs_proxy"})
                .solution(source_path() / "vsbuild" / "usvfs.sln")
                .env(env::vs(a)
                         .prepend_path(python::build_path())
                         .set("BOOST_PATH", path_to_utf8(boost::source_path()))));
    }

}  // namespace mob::tasks
